version: '3.3'

services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: grenzexpress

  backend:
    build: ./backend
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - database

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

